pygments: true
markdown: "rdiscount"

links:
  advanced_bash : [ 'advanced_bash.html', 'Advanced Bash' ]
  avoiding_common_mistakes : [ 'avoiding_common_mistakes.html', 'Avoiding Common Mistakes' ]
  bash : [ 'bash.html', 'Bash' ]
  bashrc : [ 'bashrc.html', 'bashrc' ]
  conditional_statements : [ 'conditional_statements.html', 'Conditional Statements' ]
  creating_files : [ 'creating_files.html', 'Creating Files' ]
  design : [ 'design.html', '' ]
  different_users : [ 'different_users.html', 'Different Users' ]
  environmental_variables : [ 'environmental_variables.html', 'Environmental Variables' ]
  file_permissions : [ 'file_permissions.html', 'File Permissions' ]
  file_types : [ 'file_types.html', 'File Types' ]
  getting_started : [ 'getting_started.html', 'Getting Started' ]
  home_directory_and_hidden_files : [ 'home_directory_and_hidden_files.html', 'Home Directory and Hidden Files' ]
  index : [ 'index.html', 'Intro' ]
  init : [ 'init.html', 'init' ]
  io_redirection : [ 'io_redirection.html', 'I/O Redirection' ]
  loops : [ 'loops.html', 'Loops' ]
  more_advanced_bash : [ 'more_advanced_bash.html', 'More Advanced Bash' ]
  navigation : [ 'navigation.html', 'Navigation' ]
  pipes : [ 'pipes.html', 'Pipes' ]
  processes : [ 'processes.html', 'Process' ]
  recurring_processes : [ 'recurring_processes.html', 'Recurring Processes' ]
  run_levels : [ 'run_levels.html', 'Run Levels' ]
  scripts : [ 'scripts.html', 'Scripts' ]
  terminal : [ 'terminal.html', 'Terminal' ]
  the_filesystem : [ 'the_filesystem.html', 'The Filesystem' ]
  the_unix_system : [ 'the_unix_system.html', 'The Unix System' ]
  user_environment : [ 'user_environment.html', 'User Environment' ]
